id: P006788
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18562
  title: མཇུག་དོན་ཡོངས་གཏད། བཅོས་སྒྲིག་མ།
  author: ''
  volumes:
    9e3060b3c64544e1b76e6d281b541750:
      image_group_id: I8LS18564
      title: ''
      volume_number: 1
      total_pages: 167
      base_file: v001.txt
