id: IC8F303A4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T21:35:15+00:00'
last_modified: '2022-06-08T06:51:47.101836+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18562
  title: མཇུག་དོན་ཡོངས་གཏད། བཅོས་སྒྲིག་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    4AB4:
      image_group_id: I8LS18564
      title: ''
      total_pages: 167
      order: 1
      base_file: 4AB4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
